### PR TITLE
Ignore t.Parallel goroutines, they represent queued tests

### LINKED ISSUE #16: Support t.Parallel?
Hi, thanks for providing great package :)

BTW, I saw `goleak` internal source and found below `switch...case`:
https://github.com/uber-go/goleak/blob/18742541d022941d2ef0db05d30bc68f69e96bd9/options.go#L118

But, I used `t.Parallel` func on my project testing. So, `goleak` suggested:

```
found unexpected goroutines
```

Is it the expected behavior? Or, Should I adding `goleak.IgnoreTopFunction("testing.(*T).Parallel")` to `defer goleak.VerifyNoLeaks(t)`? (and, is it correct use case?)

### PR DESCRIPTION
**Pull request by prashantv**
When t.Parallel is used, tests are queued to run after all serially
executed tests are run. This causes issues if the serial test tries to
verify goroutines.

Fixes #16

### CODE REVIEW

File: options.go [hunk 1]
```diff
@@ -115,7 +115,7 @@ func isTestStack(s stack.Stack) bool {
 	// to end by waiting on a channel.
 	// Since go1.7, a separate goroutine is started to wait for signals.
 	switch s.FirstFunction() {
-	case "testing.RunTests", "testing.(*T).Run":
+	case "testing.RunTests", "testing.(*T).Run", "testing.(*T).Parallel":
 		// In pre1.7 and post-1.7, background goroutines started by the testing
```
Comment (chucknthem) [inline options.go]: edit the comment to include t.Parallel
